package rtc

import (
	"context"
	"encoding/hex"
	"fmt"
	"sync"
	"time"

	"babylontower/pkg/identity"
	"babylontower/pkg/messaging"
	"babylontower/pkg/storage"
)

// logger is declared in session.go for this package

// CallManager provides high-level call lifecycle management
type CallManager struct {
	identity   *identity.Identity
	messaging  *messaging.Service
	storage    storage.Storage
	sessionMgr *SessionManager
	signaling  *SignalingService

	ctx    context.Context
	cancel context.CancelFunc
	wg     sync.WaitGroup

	mu sync.RWMutex

	// Current call state
	currentCallID string

	// Configuration
	config *CallConfig

	// Event callbacks
	onCallStarted   func(callID string, remoteIdentity []byte, callType string)
	onCallConnected func(callID string)
	onCallEnded     func(callID string, reason string, duration time.Duration)
	onIncomingCall  func(callID string, remoteIdentity []byte, callType string, sdp string)
	onCallError     func(callID string, err error)
}

// CallConfig holds configuration for call management
type CallConfig struct {
	// AutoAnswer determines whether to automatically answer incoming calls
	AutoAnswer bool
	// AutoAnswerTimeout is the delay before auto-answering
	AutoAnswerTimeout time.Duration
	// CallTimeout is the maximum duration for a call (0 = no limit)
	CallTimeout time.Duration
	// EnableVideo enables video calls (false = audio only)
	EnableVideo bool
	// MaxICECandidates is the maximum number of ICE candidates to gather
	MaxICECandidates int
	// ICEGatherTimeout is the timeout for ICE candidate gathering
	ICEGatherTimeout time.Duration
}

// DefaultCallConfig returns the default call configuration
func DefaultCallConfig() *CallConfig {
	return &CallConfig{
		AutoAnswer:        false,
		AutoAnswerTimeout: 0,
		CallTimeout:       0, // No limit
		EnableVideo:       true,
		MaxICECandidates:  20,
		ICEGatherTimeout:  ICEGatherTimeout,
	}
}

// NewCallManager creates a new call manager
func NewCallManager(
	id *identity.Identity,
	msgService *messaging.Service,
	store storage.Storage,
	config *CallConfig,
) (*CallManager, error) {
	if config == nil {
		config = DefaultCallConfig()
	}

	ctx, cancel := context.WithCancel(context.Background())

	// Create session manager
	sessionMgr := NewSessionManager(store, id)

	// Create signaling service
	signaling := NewSignalingService(id, msgService, sessionMgr)

	cm := &CallManager{
		identity:   id,
		messaging:  msgService,
		storage:    store,
		sessionMgr: sessionMgr,
		signaling:  signaling,
		ctx:        ctx,
		cancel:     cancel,
		config:     config,
	}

	// Set up signaling callbacks
	cm.setupSignalingCallbacks()

	return cm, nil
}

// setupSignalingCallbacks configures the signaling service callbacks
func (cm *CallManager) setupSignalingCallbacks() {
	cm.signaling.SetOnIncomingOffer(cm.handleIncomingOffer)
	cm.signaling.SetOnIncomingAnswer(cm.handleIncomingAnswer)
	cm.signaling.SetOnIncomingICE(cm.handleIncomingICE)
	cm.signaling.SetOnIncomingHangup(cm.handleIncomingHangup)

	cm.sessionMgr.SetOnStateChanged(cm.handleStateChanged)
	cm.sessionMgr.SetOnCallEnded(cm.handleSessionEnded)
}

// Start begins the call manager
func (cm *CallManager) Start() error {
	cm.mu.Lock()
	defer cm.mu.Unlock()

	if err := cm.signaling.Start(); err != nil {
		return fmt.Errorf("failed to start signaling service: %w", err)
	}

	logger.Info("Call manager started")
	return nil
}

// Stop gracefully stops the call manager and ends all active calls
func (cm *CallManager) Stop() {
	cm.mu.Lock()
	defer cm.mu.Unlock()

	// End all active calls
	sessions := cm.sessionMgr.GetAllActiveSessions()
	for _, session := range sessions {
		_ = cm.signaling.SendHangup(session.CallID, HangupNormal)
		_ = cm.sessionMgr.EndCall(session.CallID, HangupNormal)
	}

	cm.signaling.Stop()
	cm.sessionMgr.Stop()
	cm.cancel()
	cm.wg.Wait()

	logger.Info("Call manager stopped")
}

// StartOutgoingCall initiates an outgoing call to a contact
func (cm *CallManager) StartOutgoingCall(remoteIdentity []byte, callType string) (string, error) {
	cm.mu.Lock()
	defer cm.mu.Unlock()

	// Check if we're already in a call
	if cm.currentCallID != "" {
		return "", fmt.Errorf("already in call: %s", cm.currentCallID)
	}

	// Validate call type
	if callType == CallTypeVideo && !cm.config.EnableVideo {
		callType = CallTypeAudio
	}

	// Generate SDP offer (placeholder - would be generated by WebRTC)
	sdpOffer := cm.generateSDPOffer(callType)

	// Send offer via signaling
	session, err := cm.signaling.SendOffer(remoteIdentity, callType, sdpOffer)
	if err != nil {
		return "", fmt.Errorf("failed to send offer: %w", err)
	}

	cm.currentCallID = session.CallID

	logger.Infow("started outgoing call", "type", callType, "remote", hex.EncodeToString(remoteIdentity)[:16], "call", session.CallID)

	// Notify callback
	if cm.onCallStarted != nil {
		cm.onCallStarted(session.CallID, remoteIdentity, callType)
	}

	// Start call timeout if configured
	if cm.config.CallTimeout > 0 {
		go cm.startCallTimeout(session.CallID, cm.config.CallTimeout)
	}

	return session.CallID, nil
}

// AnswerIncomingCall answers an incoming call
func (cm *CallManager) AnswerIncomingCall(callID string) error {
	cm.mu.Lock()
	defer cm.mu.Unlock()

	if cm.currentCallID != "" {
		return fmt.Errorf("already in call: %s", cm.currentCallID)
	}

	session, err := cm.sessionMgr.GetSession(callID)
	if err != nil {
		return ErrCallNotFound
	}

	// Update state
	if err := cm.sessionMgr.UpdateState(callID, CallStateAccepted); err != nil {
		return fmt.Errorf("failed to update call state: %w", err)
	}

	// Generate SDP answer (placeholder)
	sdpAnswer := cm.generateSDPAnswer(session.CallType, session.RemoteSDP)

	// Send answer
	if err := cm.signaling.SendAnswer(callID, sdpAnswer); err != nil {
		return fmt.Errorf("failed to send answer: %w", err)
	}

	cm.currentCallID = callID

	logger.Infow("answered incoming call", "call", callID)

	// Notify callback
	if cm.onCallStarted != nil {
		cm.onCallStarted(callID, session.RemoteIdentity, session.CallType)
	}

	return nil
}

// RejectIncomingCall rejects an incoming call
func (cm *CallManager) RejectIncomingCall(callID string, reason string) error {
	_, err := cm.sessionMgr.GetSession(callID)
	if err != nil {
		return ErrCallNotFound
	}

	// Send hangup
	if err := cm.signaling.SendHangup(callID, reason); err != nil {
		logger.Warnw("failed to send hangup", "error", err)
	}

	// End call locally
	if err := cm.sessionMgr.EndCall(callID, reason); err != nil {
		return fmt.Errorf("failed to end call: %w", err)
	}

	logger.Infow("rejected incoming call", "call", callID, "reason", reason)

	return nil
}

// EndCall ends the current call
func (cm *CallManager) EndCall(reason string) error {
	cm.mu.Lock()
	callID := cm.currentCallID
	cm.mu.Unlock()

	if callID == "" {
		return fmt.Errorf("no active call")
	}

	return cm.EndCallByID(callID, reason)
}

// EndCallByID ends a specific call by ID
func (cm *CallManager) EndCallByID(callID string, reason string) error {
	// Send hangup
	if err := cm.signaling.SendHangup(callID, reason); err != nil {
		logger.Warnw("failed to send hangup", "error", err)
	}

	// End call locally
	if err := cm.sessionMgr.EndCall(callID, reason); err != nil {
		return fmt.Errorf("failed to end call: %w", err)
	}

	cm.mu.Lock()
	if cm.currentCallID == callID {
		cm.currentCallID = ""
	}
	cm.mu.Unlock()

	logger.Infow("ended call", "call", callID, "reason", reason)

	return nil
}

// SendICECandidate sends an ICE candidate for the current call
func (cm *CallManager) SendICECandidate(candidate string, sdpMid string, mlineIdx uint32) error {
	cm.mu.RLock()
	callID := cm.currentCallID
	cm.mu.RUnlock()

	if callID == "" {
		return fmt.Errorf("no active call")
	}

	return cm.signaling.SendICECandidate(callID, candidate, sdpMid, mlineIdx)
}

// GetActiveCall returns the current active call session
func (cm *CallManager) GetActiveCall() (*CallSession, error) {
	cm.mu.RLock()
	callID := cm.currentCallID
	cm.mu.RUnlock()

	if callID == "" {
		return nil, fmt.Errorf("no active call")
	}

	return cm.sessionMgr.GetSession(callID)
}

// GetCall returns a call session by ID
func (cm *CallManager) GetCall(callID string) (*CallSession, error) {
	return cm.sessionMgr.GetSession(callID)
}

// GetAllCalls returns all call sessions (active and ended)
func (cm *CallManager) GetAllCalls() []*CallSession {
	return cm.sessionMgr.GetAllActiveSessions()
}

// IsInCall returns true if currently in a call
func (cm *CallManager) IsInCall() bool {
	cm.mu.RLock()
	defer cm.mu.RUnlock()
	return cm.currentCallID != ""
}

// SetOnCallStarted sets the callback for when a call starts
func (cm *CallManager) SetOnCallStarted(callback func(callID string, remoteIdentity []byte, callType string)) {
	cm.mu.Lock()
	defer cm.mu.Unlock()
	cm.onCallStarted = callback
}

// SetOnCallConnected sets the callback for when a call connects
func (cm *CallManager) SetOnCallConnected(callback func(callID string)) {
	cm.mu.Lock()
	defer cm.mu.Unlock()
	cm.onCallConnected = callback
}

// SetOnCallEnded sets the callback for when a call ends
func (cm *CallManager) SetOnCallEnded(callback func(callID string, reason string, duration time.Duration)) {
	cm.mu.Lock()
	defer cm.mu.Unlock()
	cm.onCallEnded = callback
}

// SetOnIncomingCall sets the callback for incoming calls
func (cm *CallManager) SetOnIncomingCall(callback func(callID string, remoteIdentity []byte, callType string, sdp string)) {
	cm.mu.Lock()
	defer cm.mu.Unlock()
	cm.onIncomingCall = callback
}

// SetOnCallError sets the callback for call errors
func (cm *CallManager) SetOnCallError(callback func(callID string, err error)) {
	cm.mu.Lock()
	defer cm.mu.Unlock()
	cm.onCallError = callback
}

// handleIncomingOffer handles an incoming RTC offer
func (cm *CallManager) handleIncomingOffer(callID string, remoteIdentity []byte, callType string, sdp string) {
	// Notify callback
	if cm.onIncomingCall != nil {
		cm.onIncomingCall(callID, remoteIdentity, callType, sdp)
	}

	// Auto-answer if configured
	if cm.config.AutoAnswer {
		go func() {
			time.Sleep(cm.config.AutoAnswerTimeout)
			if err := cm.AnswerIncomingCall(callID); err != nil {
				logger.Errorw("failed to auto-answer call", "call", callID, "error", err)
			}
		}()
	}
}

// handleIncomingAnswer handles an incoming RTC answer
func (cm *CallManager) handleIncomingAnswer(callID string, remoteIdentity []byte, sdp string) {
	logger.Debugw("received answer for call", "call", callID)

	// Update state to connecting
	if err := cm.sessionMgr.UpdateState(callID, CallStateConnecting); err != nil {
		logger.Warnw("failed to update call state", "error", err)
	}

	// In a real implementation, this would trigger ICE connectivity checks
	// and transition to CallStateActive when media flows
}

// handleIncomingICE handles an incoming ICE candidate
func (cm *CallManager) handleIncomingICE(callID string, remoteIdentity []byte, candidate string, sdpMid string, mlineIdx uint32) {
	logger.Debugw("received ICE candidate for call", "call", callID)

	// In a real implementation, this would add the remote ICE candidate
	// and potentially trigger connectivity checks
}

// handleIncomingHangup handles an incoming hangup message
func (cm *CallManager) handleIncomingHangup(callID string, remoteIdentity []byte, reason string) {
	cm.mu.Lock()
	if cm.currentCallID == callID {
		cm.currentCallID = ""
	}
	cm.mu.Unlock()

	logger.Infow("remote peer ended call", "call", callID, "reason", reason)
}

// handleStateChanged handles call state changes
func (cm *CallManager) handleStateChanged(session *CallSession, oldState, newState string) {
	logger.Debugw("call state changed", "call", session.CallID, "old_state", oldState, "new_state", newState)

	if newState == CallStateActive && cm.onCallConnected != nil {
		cm.onCallConnected(session.CallID)
	}
}

// handleSessionEnded handles call session end events
func (cm *CallManager) handleSessionEnded(session *CallSession) {
	cm.mu.Lock()
	if cm.currentCallID == session.CallID {
		cm.currentCallID = ""
	}
	cm.mu.Unlock()

	duration := session.Duration()

	logger.Infow("call ended", "call", session.CallID, "duration", duration, "reason", session.HangupReason)

	if cm.onCallEnded != nil {
		cm.onCallEnded(session.CallID, session.HangupReason, duration)
	}
}

// startCallTimeout starts a timeout goroutine for a call
func (cm *CallManager) startCallTimeout(callID string, timeout time.Duration) {
	select {
	case <-time.After(timeout):
		logger.Warnw("call timed out", "call", callID)
		_ = cm.EndCallByID(callID, HangupTimeout)
	case <-cm.ctx.Done():
		return
	}
}

// generateSDPOffer generates a placeholder SDP offer
// In a real implementation, this would use WebRTC to generate a real SDP
func (cm *CallManager) generateSDPOffer(callType string) string {
	// This is a placeholder - in production this would use WebRTC
	// to generate a real SDP offer with actual codec negotiation
	return fmt.Sprintf(`v=0
o=- 0 0 IN IP4 127.0.0.1
s=Babylon Tower %s Call
c=IN IP4 127.0.0.1
t=0 0
m=audio 9 UDP/TLS/RTP/SAVPF 111
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10;useinbandfec=1
m=video 9 UDP/TLS/RTP/SAVPF 96
a=rtpmap:96 VP8/90000
`, callType)
}

// generateSDPAnswer generates a placeholder SDP answer
func (cm *CallManager) generateSDPAnswer(callType string, remoteSDP string) string {
	// This is a placeholder - in production this would use WebRTC
	// to generate a real SDP answer based on the remote offer
	return fmt.Sprintf(`v=0
o=- 0 0 IN IP4 127.0.0.1
s=Babylon Tower %s Call (Answer)
c=IN IP4 127.0.0.1
t=0 0
m=audio 9 UDP/TLS/RTP/SAVPF 111
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10;useinbandfec=1
m=video 9 UDP/TLS/RTP/SAVPF 96
a=rtpmap:96 VP8/90000
`, callType)
}
